# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parameters.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='parameters.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x10parameters.proto\"\x8b\x07\n\x13StyleTransferParams\x12\x11\n\tin_memory\x18\x01 \x01(\x08\x12\x0f\n\x07max_len\x18\x02 \x01(\x05\x12\x16\n\x0e\x65mbedding_size\x18\x03 \x01(\x05\x12\r\n\x05\x64im_y\x18\x04 \x01(\x05\x12\r\n\x05\x64im_z\x18\x05 \x01(\x05\x12\x12\n\nbatch_size\x18\x06 \x01(\x05\x12\x0e\n\x06\x65pochs\x18\x07 \x01(\x05\x12\x13\n\x0btemperature\x18\x08 \x01(\x02\x12\x12\n\nlambda_GAN\x18\t \x01(\x02\x12\x0f\n\x07\x64ropout\x18\n \x01(\x02\x12\x10\n\x08max_loss\x18\x0b \x01(\x02\x12\x11\n\tgrad_clip\x18\x0c \x01(\x02\x12\x12\n\nmax_d_loss\x18\r \x01(\x02\x12\x10\n\x08savefile\x18\x0e \x01(\t\x12\x0e\n\x06logdir\x18\x0f \x01(\t\x12\x12\n\nbeam_width\x18\x10 \x01(\x05\x12\x15\n\rinitial_noise\x18\x11 \x01(\x02\x12\x13\n\x0bnoise_decay\x18\x12 \x01(\x02\x12;\n\x0b\x61utoencoder\x18\x13 \x01(\x0b\x32&.StyleTransferParams.AutoencoderParams\x12?\n\rdiscriminator\x18\x14 \x01(\x0b\x32(.StyleTransferParams.DiscriminatorParams\x1a\xf4\x01\n\x13\x44iscriminatorParams\x12\x13\n\x0bin_channels\x18\x01 \x01(\x05\x12\x14\n\x0cout_channels\x18\x02 \x01(\x05\x12\x14\n\x0ckernel_sizes\x18\x03 \x03(\x05\x12\x16\n\x0e\x65mbedding_size\x18\x04 \x01(\x05\x12\x13\n\x0bhidden_size\x18\x05 \x01(\x05\x12\x0f\n\x07\x64ropout\x18\x06 \x01(\x02\x12\x15\n\rlearning_rate\x18\x07 \x01(\x02\x12\x0e\n\x06\x62\x65ta_0\x18\x08 \x01(\x02\x12\x0e\n\x06\x62\x65ta_1\x18\t \x01(\x02\x12\x13\n\x0bl_smoothing\x18\n \x01(\x02\x12\x12\n\nl_flipping\x18\x0b \x01(\x02\x1a\xab\x01\n\x11\x41utoencoderParams\x12\x12\n\ninput_size\x18\x01 \x01(\x05\x12\x13\n\x0bhidden_size\x18\x02 \x01(\x05\x12\x12\n\nnum_layers\x18\x03 \x01(\x05\x12\x0f\n\x07\x64ropout\x18\x04 \x01(\x02\x12\x15\n\rlearning_rate\x18\x05 \x01(\x02\x12\x0e\n\x06\x62\x65ta_0\x18\x06 \x01(\x02\x12\x0e\n\x06\x62\x65ta_1\x18\x07 \x01(\x02\x12\x11\n\tword_drop\x18\x08 \x01(\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_STYLETRANSFERPARAMS_DISCRIMINATORPARAMS = _descriptor.Descriptor(
  name='DiscriminatorParams',
  full_name='StyleTransferParams.DiscriminatorParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='in_channels', full_name='StyleTransferParams.DiscriminatorParams.in_channels', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='out_channels', full_name='StyleTransferParams.DiscriminatorParams.out_channels', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kernel_sizes', full_name='StyleTransferParams.DiscriminatorParams.kernel_sizes', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='embedding_size', full_name='StyleTransferParams.DiscriminatorParams.embedding_size', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hidden_size', full_name='StyleTransferParams.DiscriminatorParams.hidden_size', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dropout', full_name='StyleTransferParams.DiscriminatorParams.dropout', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='learning_rate', full_name='StyleTransferParams.DiscriminatorParams.learning_rate', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='beta_0', full_name='StyleTransferParams.DiscriminatorParams.beta_0', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='beta_1', full_name='StyleTransferParams.DiscriminatorParams.beta_1', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l_smoothing', full_name='StyleTransferParams.DiscriminatorParams.l_smoothing', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l_flipping', full_name='StyleTransferParams.DiscriminatorParams.l_flipping', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=510,
  serialized_end=754,
)

_STYLETRANSFERPARAMS_AUTOENCODERPARAMS = _descriptor.Descriptor(
  name='AutoencoderParams',
  full_name='StyleTransferParams.AutoencoderParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_size', full_name='StyleTransferParams.AutoencoderParams.input_size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hidden_size', full_name='StyleTransferParams.AutoencoderParams.hidden_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_layers', full_name='StyleTransferParams.AutoencoderParams.num_layers', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dropout', full_name='StyleTransferParams.AutoencoderParams.dropout', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='learning_rate', full_name='StyleTransferParams.AutoencoderParams.learning_rate', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='beta_0', full_name='StyleTransferParams.AutoencoderParams.beta_0', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='beta_1', full_name='StyleTransferParams.AutoencoderParams.beta_1', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='word_drop', full_name='StyleTransferParams.AutoencoderParams.word_drop', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=757,
  serialized_end=928,
)

_STYLETRANSFERPARAMS = _descriptor.Descriptor(
  name='StyleTransferParams',
  full_name='StyleTransferParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='in_memory', full_name='StyleTransferParams.in_memory', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_len', full_name='StyleTransferParams.max_len', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='embedding_size', full_name='StyleTransferParams.embedding_size', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dim_y', full_name='StyleTransferParams.dim_y', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dim_z', full_name='StyleTransferParams.dim_z', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='StyleTransferParams.batch_size', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='epochs', full_name='StyleTransferParams.epochs', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='StyleTransferParams.temperature', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lambda_GAN', full_name='StyleTransferParams.lambda_GAN', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dropout', full_name='StyleTransferParams.dropout', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_loss', full_name='StyleTransferParams.max_loss', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='grad_clip', full_name='StyleTransferParams.grad_clip', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_d_loss', full_name='StyleTransferParams.max_d_loss', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='savefile', full_name='StyleTransferParams.savefile', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='logdir', full_name='StyleTransferParams.logdir', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='beam_width', full_name='StyleTransferParams.beam_width', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='initial_noise', full_name='StyleTransferParams.initial_noise', index=16,
      number=17, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='noise_decay', full_name='StyleTransferParams.noise_decay', index=17,
      number=18, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='autoencoder', full_name='StyleTransferParams.autoencoder', index=18,
      number=19, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='discriminator', full_name='StyleTransferParams.discriminator', index=19,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_STYLETRANSFERPARAMS_DISCRIMINATORPARAMS, _STYLETRANSFERPARAMS_AUTOENCODERPARAMS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=928,
)

_STYLETRANSFERPARAMS_DISCRIMINATORPARAMS.containing_type = _STYLETRANSFERPARAMS
_STYLETRANSFERPARAMS_AUTOENCODERPARAMS.containing_type = _STYLETRANSFERPARAMS
_STYLETRANSFERPARAMS.fields_by_name['autoencoder'].message_type = _STYLETRANSFERPARAMS_AUTOENCODERPARAMS
_STYLETRANSFERPARAMS.fields_by_name['discriminator'].message_type = _STYLETRANSFERPARAMS_DISCRIMINATORPARAMS
DESCRIPTOR.message_types_by_name['StyleTransferParams'] = _STYLETRANSFERPARAMS

StyleTransferParams = _reflection.GeneratedProtocolMessageType('StyleTransferParams', (_message.Message,), dict(

  DiscriminatorParams = _reflection.GeneratedProtocolMessageType('DiscriminatorParams', (_message.Message,), dict(
    DESCRIPTOR = _STYLETRANSFERPARAMS_DISCRIMINATORPARAMS,
    __module__ = 'parameters_pb2'
    # @@protoc_insertion_point(class_scope:StyleTransferParams.DiscriminatorParams)
    ))
  ,

  AutoencoderParams = _reflection.GeneratedProtocolMessageType('AutoencoderParams', (_message.Message,), dict(
    DESCRIPTOR = _STYLETRANSFERPARAMS_AUTOENCODERPARAMS,
    __module__ = 'parameters_pb2'
    # @@protoc_insertion_point(class_scope:StyleTransferParams.AutoencoderParams)
    ))
  ,
  DESCRIPTOR = _STYLETRANSFERPARAMS,
  __module__ = 'parameters_pb2'
  # @@protoc_insertion_point(class_scope:StyleTransferParams)
  ))
_sym_db.RegisterMessage(StyleTransferParams)
_sym_db.RegisterMessage(StyleTransferParams.DiscriminatorParams)
_sym_db.RegisterMessage(StyleTransferParams.AutoencoderParams)


# @@protoc_insertion_point(module_scope)
